### ISSUE TITLE
Add Components Page

### ISSUE THREAD

**Issue by Icosahunter** [mechtronica/mechtronica.net#10]
Add a new components page to the mech building section that explains each subsystem and each component within that subsystem.

- [x] Components Page
    - [x] Frames
    - [x] Plating
    - [x] Cabins
    - [x] Mainframes
    - [x] Modules
    - [x] Coolers
    - [x] Power Plants
    - [x] Fuel Tanks
    - [x] Weapons
    - [x] Equipment

**Comment by infinitymdm** [comment]
I think the issue here is that we have different ideas for how we want things to flow. With the current implementation, I'm trying to bring the reader through the following:

- Planning: explain key decisions (mostly frame size and power type) that have major effects on play style
- Selecting Components: drill down into component details, why you might want one component over another, etc. This is where the meat of the section will be (and this might need to be broken into several smaller pages, perhaps including a Components page)
- Placing Components: explain component slots and factors you want to consider when placing components
- Validating: Resource calculations and things to double check (needs more work as mentioned in #9 )

I think we may need to agree on a flow to walk readers through, and then start making changes. Do you have some thoughts on how you think this ought to flow?

**Comment by Icosahunter** [comment]
In my mind explaining the mechanics is a bit separate from explaining how to build a mech well. My idea was something along the lines of:

- Overview: Explain components and interactions at a high level
- Components: Go into detail on each subsystem and component and any details about it
- Planning: Explain the strategic decisions that need to be made
- Placing
- Validating

I think why you would want to select one component over another should be explained in planning, or something like that. It sounds like your Selecting Components it's a bit of a mix between my Components and the existing Planning, and it seems reasonable to break that out. Whichever way I think we do need a page that just lists the components and describes them, as it would be a bit frustrating as a reader that's trying to get to the meat of things quickly to not be able to just find that stuff by itself.

**Comment by infinitymdm** [comment]
I think I can make something like that work. Probably also good to link to link back to the Components page in the Planning page, so that relevant information is still close by.

**Comment by infinitymdm** [comment]
Moving the other pages (Overview, Planning, Validating, and Placing) to their own issues.
